"""
Air Quality LSTM Training Script
Predicts PM10 and PM25 from 24-hour historical sequences.

Architecture: LSTM (seq2point) — 24h input window → [pm10, pm25] at next hour
Dataset    : air_quality_train.csv (generated by generate_dataset.py)

Usage:
    python train_model.py
    python train_model.py --epochs 100 --batch 512 --seq 48
"""

import os
import sys
import time
import json
import argparse
import math

# ── Apple Silicon OpenMP conflict fix ──────────────────────────────────────────
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
from tqdm import tqdm

# ─────────────────────────── CLI args ─────────────────────────────────────────
parser = argparse.ArgumentParser()
parser.add_argument("--epochs",   type=int,   default=50)
parser.add_argument("--batch",    type=int,   default=256)
parser.add_argument("--seq",      type=int,   default=24,   help="input sequence length (hours)")
parser.add_argument("--hidden",   type=int,   default=128)
parser.add_argument("--layers",   type=int,   default=2)
parser.add_argument("--dropout",  type=float, default=0.2)
parser.add_argument("--lr",       type=float, default=1e-3)
parser.add_argument("--csv",      type=str,   default="air_quality_train.csv")
parser.add_argument("--out",      type=str,   default="model_output")
args = parser.parse_args()

# ─────────────────────────── DEVICE ───────────────────────────────────────────
if torch.backends.mps.is_available():
    DEVICE = torch.device("mps")
elif torch.cuda.is_available():
    DEVICE = torch.device("cuda")
else:
    DEVICE = torch.device("cpu")

# ─────────────────────────── FEATURES ─────────────────────────────────────────
# Input features fed into each timestep of the LSTM sequence
FEATURE_COLS = [
    # temporal
    "hour", "month", "day_of_week", "season",
    # meteorological
    "temperature", "humidity", "dew_point",
    "wind_speed", "wind_direction", "pressure",
    # co-pollutants
    "no2", "so2", "co", "o3",
    # previous PM values (inside the sequence window)
    "pm10", "pm25",
]

TARGET_COLS = ["pm10", "pm25"]   # what we predict at hour t+1

# ─────────────────────────── HELPERS ──────────────────────────────────────────
def print_header(title: str):
    width = 60
    print("\n" + "═" * width)
    print(f"  {title}")
    print("═" * width)

def format_metrics(d: dict) -> str:
    return "  ".join(f"{k}: {v:.4f}" for k, v in d.items())

def rmse(a, b):
    return math.sqrt(((a - b) ** 2).mean())

# ─────────────────────────── DATASET ──────────────────────────────────────────
class AirQualityDataset(Dataset):
    """
    Sliding-window sequence dataset.
    Each sample: (seq_len × n_features) → (pm10, pm25) at t+1
    """
    def __init__(self, sequences, targets):
        self.X = torch.tensor(sequences, dtype=torch.float32)
        self.y = torch.tensor(targets,   dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


def build_sequences(df: pd.DataFrame, seq_len: int, scaler: StandardScaler = None,
                    fit_scaler: bool = False):
    """
    Groups by district, sorts by time, creates sliding windows.
    Returns (sequences, targets, scaler).
    """
    df = df.sort_values(["district", "date", "hour"]).reset_index(drop=True)
    feature_data = df[FEATURE_COLS].values.astype(np.float32)

    if fit_scaler:
        scaler = StandardScaler()
        feature_data = scaler.fit_transform(feature_data)
    else:
        feature_data = scaler.transform(feature_data)

    target_data = df[TARGET_COLS].values.astype(np.float32)

    sequences, targets = [], []
    districts = df["district"].values

    # Build sequences — skip window across district boundaries
    n = len(df)
    for i in range(seq_len, n):
        # Ensure entire window belongs to the same district
        if districts[i - seq_len] != districts[i]:
            continue
        sequences.append(feature_data[i - seq_len : i])   # (seq_len, n_features)
        targets.append(target_data[i])                     # (pm10, pm25) at time i

    return np.array(sequences, dtype=np.float32), np.array(targets, dtype=np.float32), scaler

# ─────────────────────────── MODEL ────────────────────────────────────────────
class AirQualityLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, dropout, output_size=2):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head = nn.Sequential(
            nn.LayerNorm(hidden_size),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Linear(hidden_size // 2, output_size),
            nn.ReLU(),   # PM values are always ≥ 0
        )

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.head(out[:, -1, :])   # use last timestep

# ─────────────────────────── TRAIN / EVAL LOOPS ───────────────────────────────
def run_epoch(model, loader, criterion, optimizer=None, device=DEVICE):
    """Single train or eval pass. Returns avg loss and per-target MAE."""
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    total_loss = 0.0
    all_preds, all_targets = [], []

    ctx = torch.enable_grad() if is_train else torch.no_grad()
    with ctx:
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            preds = model(X_batch)
            loss  = criterion(preds, y_batch)

            if is_train:
                optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item() * len(y_batch)
            all_preds.append(preds.detach().cpu().numpy())
            all_targets.append(y_batch.detach().cpu().numpy())

    preds_np   = np.concatenate(all_preds)
    targets_np = np.concatenate(all_targets)

    avg_loss      = total_loss / len(loader.dataset)
    mae_pm10      = float(np.abs(preds_np[:, 0] - targets_np[:, 0]).mean())
    mae_pm25      = float(np.abs(preds_np[:, 1] - targets_np[:, 1]).mean())
    rmse_pm10     = float(rmse(preds_np[:, 0], targets_np[:, 0]))
    rmse_pm25     = float(rmse(preds_np[:, 1], targets_np[:, 1]))

    return avg_loss, mae_pm10, mae_pm25, rmse_pm10, rmse_pm25

# ─────────────────────────── MAIN ─────────────────────────────────────────────
def main():
    os.makedirs(args.out, exist_ok=True)

    print_header("AIR QUALITY LSTM TRAINER")
    print(f"  Device   : {DEVICE}")
    print(f"  Seq len  : {args.seq} hours")
    print(f"  Hidden   : {args.hidden}  ×  {args.layers} layers")
    print(f"  Epochs   : {args.epochs}   Batch: {args.batch}   LR: {args.lr}")

    # ── 1. Load data ───────────────────────────────────────────────────────────
    print_header("1. Loading data")
    print(f"  Reading {args.csv} ...", end=" ", flush=True)
    df = pd.read_csv(args.csv)
    print(f"done  ({len(df):,} rows)")

    # Time-based split — never shuffle time series!
    dates = sorted(df["date"].unique())
    n = len(dates)
    train_end = dates[int(n * 0.70)]
    val_end   = dates[int(n * 0.85)]

    df_train = df[df["date"] <= train_end].copy()
    df_val   = df[(df["date"] > train_end) & (df["date"] <= val_end)].copy()
    df_test  = df[df["date"] > val_end].copy()

    print(f"  Train : {df_train['date'].min()} ~ {df_train['date'].max()}  "
          f"({len(df_train):,} rows)")
    print(f"  Val   : {df_val['date'].min()}   ~ {df_val['date'].max()}  "
          f"({len(df_val):,} rows)")
    print(f"  Test  : {df_test['date'].min()}  ~ {df_test['date'].max()}  "
          f"({len(df_test):,} rows)")

    # ── 2. Build sequences ─────────────────────────────────────────────────────
    print_header("2. Building sequences")
    X_train, y_train, scaler = build_sequences(df_train, args.seq, fit_scaler=True)
    X_val,   y_val,   _      = build_sequences(df_val,   args.seq, scaler=scaler)
    X_test,  y_test,  _      = build_sequences(df_test,  args.seq, scaler=scaler)

    print(f"  Train  : {len(X_train):>7,} sequences")
    print(f"  Val    : {len(X_val):>7,} sequences")
    print(f"  Test   : {len(X_test):>7,} sequences")
    print(f"  Shape  : {X_train.shape}  (seq_len × {len(FEATURE_COLS)} features)")

    # Save scaler for inference
    import pickle
    with open(os.path.join(args.out, "scaler.pkl"), "wb") as f:
        pickle.dump(scaler, f)

    # ── 3. DataLoaders ─────────────────────────────────────────────────────────
    train_ds  = AirQualityDataset(X_train, y_train)
    val_ds    = AirQualityDataset(X_val,   y_val)
    test_ds   = AirQualityDataset(X_test,  y_test)

    train_loader = DataLoader(train_ds, batch_size=args.batch, shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch, shuffle=False, num_workers=0)
    test_loader  = DataLoader(test_ds,  batch_size=args.batch, shuffle=False, num_workers=0)

    # ── 4. Model ───────────────────────────────────────────────────────────────
    print_header("3. Building model")
    model = AirQualityLSTM(
        input_size  = len(FEATURE_COLS),
        hidden_size = args.hidden,
        num_layers  = args.layers,
        dropout     = args.dropout,
    ).to(DEVICE)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"  Parameters : {total_params:,}")
    print(f"  Architecture:")
    print(f"    LSTM({len(FEATURE_COLS)} → {args.hidden}, layers={args.layers})")
    print(f"    LayerNorm → Dropout → Linear({args.hidden} → {args.hidden//2}) → ReLU → Linear → ReLU")

    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=5, verbose=False
    )

    # ── 5. Training loop ───────────────────────────────────────────────────────
    print_header("4. Training")

    best_val_loss = float("inf")
    best_epoch    = 0
    history       = []
    ckpt_path     = os.path.join(args.out, "best_model.pt")

    epoch_bar = tqdm(range(1, args.epochs + 1), desc="Epochs", unit="ep",
                     ncols=80, colour="cyan")

    for epoch in epoch_bar:
        t0 = time.time()

        tr_loss, tr_m10, tr_m25, tr_r10, tr_r25 = run_epoch(
            model, train_loader, criterion, optimizer
        )
        va_loss, va_m10, va_m25, va_r10, va_r25 = run_epoch(
            model, val_loader, criterion
        )

        scheduler.step(va_loss)
        elapsed = time.time() - t0
        lr_now  = optimizer.param_groups[0]["lr"]

        # Save best checkpoint
        is_best = va_loss < best_val_loss
        if is_best:
            best_val_loss = va_loss
            best_epoch    = epoch
            torch.save(model.state_dict(), ckpt_path)

        # tqdm postfix (shown inline next to the bar)
        epoch_bar.set_postfix({
            "tr_loss": f"{tr_loss:.3f}",
            "va_loss": f"{va_loss:.3f}",
            "MAE10":   f"{va_m10:.1f}",
            "MAE25":   f"{va_m25:.1f}",
            "best":    f"ep{best_epoch}",
        })

        # Detailed line every 5 epochs
        if epoch % 5 == 0 or epoch == 1 or is_best:
            marker = " ★ BEST" if is_best else ""
            tqdm.write(
                f"  ep {epoch:03d}/{args.epochs}"
                f"  train={tr_loss:.4f}  val={va_loss:.4f}"
                f"  │ PM10  MAE={va_m10:5.1f} RMSE={va_r10:5.1f}"
                f"  │ PM25  MAE={va_m25:5.1f} RMSE={va_r25:5.1f}"
                f"  │ lr={lr_now:.2e}  {elapsed:.1f}s{marker}"
            )

        row = dict(epoch=epoch, train_loss=tr_loss, val_loss=va_loss,
                   val_mae_pm10=va_m10, val_mae_pm25=va_m25,
                   val_rmse_pm10=va_r10, val_rmse_pm25=va_r25, lr=lr_now)
        history.append(row)

    epoch_bar.close()

    # ── 6. Test evaluation ─────────────────────────────────────────────────────
    print_header("5. Test Evaluation")
    print(f"  Loading best checkpoint (epoch {best_epoch}) ...")
    model.load_state_dict(torch.load(ckpt_path, map_location=DEVICE))

    te_loss, te_m10, te_m25, te_r10, te_r25 = run_epoch(
        model, test_loader, criterion
    )

    print(f"""
  ┌─────────────────────────────────────────────┐
  │           TEST SET RESULTS                  │
  ├──────────────┬──────────────┬───────────────┤
  │              │   PM10       │   PM25        │
  ├──────────────┼──────────────┼───────────────┤
  │  MAE  (μg/m³)│  {te_m10:>8.2f}    │  {te_m25:>8.2f}     │
  │  RMSE (μg/m³)│  {te_r10:>8.2f}    │  {te_r25:>8.2f}     │
  │  MSE  (loss) │  {te_loss:>8.4f}    │               │
  └──────────────┴──────────────┴───────────────┘
    """)

    # ── 7. Save artifacts ──────────────────────────────────────────────────────
    print_header("6. Saving artifacts")

    # Training history JSON
    history_path = os.path.join(args.out, "history.json")
    with open(history_path, "w") as f:
        json.dump(history, f, indent=2)

    # Model config (needed for inference)
    config = {
        "input_size":  len(FEATURE_COLS),
        "hidden_size": args.hidden,
        "num_layers":  args.layers,
        "dropout":     args.dropout,
        "seq_len":     args.seq,
        "features":    FEATURE_COLS,
        "targets":     TARGET_COLS,
        "best_epoch":  best_epoch,
        "test_mae_pm10":  te_m10,
        "test_mae_pm25":  te_m25,
        "test_rmse_pm10": te_r10,
        "test_rmse_pm25": te_r25,
    }
    config_path = os.path.join(args.out, "model_config.json")
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"  {ckpt_path}")
    print(f"  {history_path}")
    print(f"  {config_path}")
    print(f"  {os.path.join(args.out, 'scaler.pkl')}")
    print(f"\n  Done. Best val loss = {best_val_loss:.4f}  (epoch {best_epoch})")


if __name__ == "__main__":
    main()
